const CATALOG = [
    {
        id: "pt1",
        name: "PLANTLIM",
        img: "/img/printer1.jpg",
        price: 10000,
        sil: "#",
    },
    {
        id: "pt2",
        name: "HP",
        img: "/img/printer2.jpg",
        price: 12000,
        sil: "#",
    },
    {
        id: "pt3",
        name: "XEROX",
        img: "/img/printer3.jpg",
        price: 8000,
        sil: "#",
    },
    {
        id: "pt4",
        name: "PANRUM M6502",
        img: "/img/printer4.webp",
        price: 12500,
        sil: "#",
    },
    {
        id: "pt5",
        name: "KYOCER FS-1025",
        img: "/img/printer5.jpg",
        price: 60000,
        sil: "#",
    },
    {
        id: "pt6",
        name: "XEROX WORKCENTER 3025BI",
        img: "/img/printer 6.jpg",
        price: 21000,
        sil: "#",
    },
    {
        id: "pt7",
        name: "RICOH M C240FW",
        img: "/img/printer7.jpg",
        price: 53500,
        sil: "#",
    },
    {
        id: "pt8",
        name: "HP LASER MFP 136A",
        img: "/img/printer8.jpg",
        price: 18400,
        sil: "#",
    },
    {
        id: "pt9",
        name: "HUAWEI PIXLAB X1",
        img: "/img/printer9.jpg",
        price: 21000,
        sil: "#",
    },
]